# Generated by Django 5.2.4 on 2025-07-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisteredSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=128, null=True)),
                ('additional_description', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('fork', 'Fork'), ('shock', 'Rear Shock'), ('dropper', 'Dropper Post'), ('other', 'Other')], max_length=128)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'serial_number'), name='unique_serial_number_per_user')],
            },
        ),
    ]
