# Generated by Django 5.2.4 on 2025-07-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisteredsuspension',
            name='additional_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='SuspensionServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('type_of_service', models.CharField(max_length=256)),
                ('serviced_by', models.CharField(max_length=256)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='service_invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='suspension.userregisteredsuspension')),
            ],
        ),
    ]
